name = "DataVoyager"
uuid = "5721bf48-af8e-5845-8445-c9e18126e773"
version = "1.0.0-DEV"

[deps]
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
DataValues = "≥ 0.4.4"
Electron = "0.2, 0.3, 0.4, 1"
IterableTables = "0.8.3, 0.9, 0.10, 0.11, 1"
IteratorInterfaceExtensions = "^0.1.1, ^1"
JSON = "≥ 0.19.0"
TableTraits = "^0.3.1, ^0.4, ^1"
URIParser = "≥ 0.4.0"
VegaLite = "≥ 0.4.0"
julia = "1"
